SELECT MONITORING_POINT,START_DATE,ORIGIN_ADDRESS,RECORD_TYPE,SUM(EVENT_DURATION),SUM(CDR_COUNT),SUM(DATA_VOLUME)
                    FROM RPETEUCDAT.ROAM_TAP_AGG
                    WHERE START_DATE Like '%' || ? || '%'
                    GROUP BY MONITORING_POINT,START_DATE,ORIGIN_ADDRESS,RECORD_TYPE
                    ORDER BY START_DATE

					